Add content
canada-ca/design-system-systeme-conception pull request #70
Opened 2019-12-16 20:10 UTC by delisma

2019-12-16 20:24 UTC, nschonni requested changes

2019-12-16 20:24 UTC, nschonni commented on index.html
> +	layout: splashpage.html
might need to remove the leading whitespace, but I'm not sure

2019-12-16 20:24 UTC, nschonni commented on index.html
> +	permalink: design-conception.canaca.ca/index.html
```suggestion
	permalink: design-conception.canada.ca/index.html
```

2019-12-16 20:24 UTC, nschonni commented on index.html
> +<div class="sp-hb">
It seems like most of this should be coming from the root template, and this page just should be metadate only for the template values

2019-12-16 20:47 UTC, Borges-Porteous commented on index.html
> +	permalink: design-conception.canaca.ca/index.html
I think we should also just stick to design.canada.ca for the bilingual repo.

Both Montreal and the Quebec governments are using "design" not conception. In @quidampepin 's words, we don't want to be more catholic than the pope.

2019-12-16 20:49 UTC, Borges-Porteous commented on index.html
> +<div class="sp-hb">
We've also been adding a JSON-LD snippet for schema.org metadata, contextual to the page. How can we keep that when using jekyll?

See example on [radio buttons page](https://github.com/canada-ca/design-system/blob/master/components/radio-buttons.html)

2019-12-17 13:23 UTC, delisma commented on index.html
> +	permalink: design-conception.canaca.ca/index.html
@Borges-Porteous The design-conception.canada.ca is the URL for the splashpage. The actual URL for the repo would be design.canada.ca for the English content and conception.canada.ca for the French content. 

If "design" flies with OL/LO we might not need the pope's approval.

2019-12-17 13:28 UTC, delisma commented on index.html
> +<div class="sp-hb">
That's why I did this file only. Wanted to see how the content should be added when there's a lot of customization to declare. Still figuring it out. Will update the Jekyll template.

2019-12-17 13:29 UTC, delisma commented on index.html
> +	layout: splashpage.html
Wasn't sure either. Was just following WET-BOEW-documentation example...I think

2019-12-17 13:54 UTC, delisma commented on index.html
> +<div class="sp-hb">
> We've also been adding a JSON-LD snippet for schema.org metadata, contextual to the page. How can we keep that when using jekyll?
> 
> See example on [radio buttons page](https://github.com/canada-ca/design-system/blob/master/components/radio-buttons.html)

I think it's doable with Jekyll. I'll check with @duboisp today

2020-01-16 17:03 UTC, delisma commented on index.html
> +<div class="sp-hb">
It's done in the wet-boew/gweb-jekyll repo that we're calling in through `remote_theme`

2020-01-16 17:03 UTC, closed without merging