Updates to how to get started
canada-ca/design-system-systeme-conception pull request #76
Opened 2020-01-27 17:10 UTC by Borges-Porteous

2020-01-27 19:53 UTC, delisma commented on .bundle/config
> +BUNDLE_PATH: "vendor/bundle"
Was that created by the `bundle` command or you created it yourself?

2020-01-27 20:53 UTC, Borges-Porteous commented on .bundle/config
> +BUNDLE_PATH: "vendor/bundle"
Was automatically done, no idea

2020-01-27 20:55 UTC, Borges-Porteous commented
Question for you @delisma now that I've made some updates, how should I proceed to share the preview with colleagues and get their input? I guess I have to push it back to gh-pages to get it working live? (other than just changing the branch making the github preview...)

2020-01-28 12:40 UTC, delisma commented on .bundle/config
> +BUNDLE_PATH: "vendor/bundle"
@Borges-Porteous can you add `.bundle` in the `.gitignore` file please?

2020-01-28 12:44 UTC, delisma commented
> Question for you @delisma now that I've made some updates, how should I proceed to share the preview with colleagues and get their input? I guess I have to push it back to gh-pages to get it working live? (other than just changing the branch making the github preview...)

@Borges-Porteous This is where the Netlify workflow would shine. Unfortunately we can only publish one branch on GitHub but on Netlify any branch can be published. Otherwise we all need to sync up the repo to get your changes locally and than serve on our individual machine, which I think is possible.
/cc @nschonni

2020-01-28 13:07 UTC, quidampepin approved these changes
Looks good to me as a starting point.

2020-01-28 13:12 UTC, delisma requested changes
@Borges-Porteous Add this line in your `.gitignore` file under the Jekyll site files
`.bundle`

2020-01-28 17:38 UTC, nschonni commented
General note, since you're working with source control now, it might be better to delete the sections rather than commenting them out. The can be pulled back out of the history later if you need them

2020-01-28 17:49 UTC, merged

2020-01-28 17:51 UTC, Borges-Porteous commented
> General note, since you're working with source control now, it might be better to delete the sections rather than commenting them out. The can be pulled back out of the history later if you need them

Haha, you're really paying attention to the changes! Sounds good, 

I was just hesitant with these particular sections since rather than delete them, they probably should exist on a different section: we need the latest updates somewhere, but in the get started section might not be the place.

2020-01-28 17:52 UTC, Borges-Porteous commented
Note that I've merged it back into gh-pages. Since the gh-pages is draft anyway, need it there to share with the team along with the community pages that David is going to share.

We can improve our branch draft process with Netlify... looking forward to that.