Modifying IA based on testing
canada-ca/design-system-systeme-conception pull request #88
Opened 2020-02-21 13:06 UTC by quidampepin

2020-02-26 21:16 UTC, delisma reviewed
Pourquoi ne pas utiliser du Markdown pour le contenu d'un bon nombre de ces pages? Ça permettrait de démontrer que même sans une experience de codage exhaustive on peut quand même contribuer au système de conception.

cc @Borges-Porteous

2020-02-27 14:25 UTC, delisma reviewed
Il semble que la structure de fichiers en anglais n'est pas la même qu'en français. Est-ce que c'est intentionnel?

2020-02-27 16:12 UTC, delisma requested changes

2020-02-27 16:12 UTC, delisma commented on _pages/en/write.md
> +      <h3><a href="../solutions/design-for-task-success">Design for task success</a></h3>
Je ne trouve pas cette page. Est-ce un lien pour une page futur?

2020-02-27 16:12 UTC, delisma commented on _pages/en/write/search.md
> +    link: "/en/write"
Le breadcrumb de `content-design-tips`, `content-style-guide`, `claiming-knowledge-panels`,  `optimizing-content-for-search` devrait émuler celui de `search` sinon cela crée un lien brisé.

2020-02-27 16:12 UTC, delisma commented on _pages/en/write/search.md
> +    link: "/en/write"
`altLangPrefix: /conception-contenu/recherche` n'existe plus en français. Il faudrait le pointer vers `redaction/recherche` je crois sans le `/` au début.

2020-02-27 16:12 UTC, delisma commented on _pages/fr/debuter/changements.md
> +altLangPrefix: /get-started/latest
Le premier `/` doit être enlevé

2020-02-27 16:12 UTC, delisma commented on _pages/fr/debuter/comment.md
> +altLangPrefix: /get-started/how
Le premier `/` doit être enlevé

2020-02-27 16:24 UTC, quidampepin commented on _pages/en/write.md
> +      <h3><a href="../solutions/design-for-task-success">Design for task success</a></h3>
Oui, un placeholder pour le "guide d'optimisation" sur lequel Scott travaille.

2020-02-27 16:24 UTC, quidampepin commented on _pages/en/write.md
> +      <h3><a href="../solutions/design-for-task-success">Design for task success</a></h3>
Comme la page n'existe pas, je vais simplement enlever le lien pour le moment...

2020-02-27 16:32 UTC, quidampepin commented on _pages/en/write.md
> +      <h3><a href="../solutions/design-for-task-success">Design for task success</a></h3>
J'ai renommé la page "Content  design tips" pour qu'elle soit cette page (design for task success)

2020-02-27 16:34 UTC, quidampepin commented on _pages/fr/debuter/comment.md
> +altLangPrefix: /get-started/how
Done

2020-02-27 16:34 UTC, quidampepin commented on _pages/fr/debuter/changements.md
> +altLangPrefix: /get-started/latest
done

2020-02-27 16:35 UTC, quidampepin commented on _pages/en/write/search.md
> +    link: "/en/write"
done

2020-02-27 19:32 UTC, delisma requested changes
Quelques changements et on est bon

2020-02-27 19:32 UTC, delisma commented on _pages/en/get-started/how.md
> +altLangPrefix: /debuter/comment
Tous les `/` du début sont à enlever dans le paramètre `altLangPrefix`

2020-02-27 19:32 UTC, delisma commented on _pages/en/get-started/information-architecture.md
> +altLangPrefix: /debuter/architecture-information
Le `/` du début est à enlever

2020-02-27 19:32 UTC, delisma commented on _pages/en/get-started/latest.md
> +altLangPrefix: /debuter/changements
Le `/` du début est à enlever

2020-02-27 19:32 UTC, delisma commented on _pages/en/get-started/policies.md
> +altLangPrefix: /debuter/politiques
Le `/` du début est à enlever

2020-02-27 19:32 UTC, delisma commented on _pages/en/get-started/who.md
> +altLangPrefix: /debuter/qui
Le `/` du début est à enlever

2020-02-27 19:32 UTC, delisma commented on _pages/fr/redaction/concevoir-succes-taches.md
> +- title: "Accueil"
Il manque la clé `breadcrumbs` à la ligne 4

2020-02-27 19:32 UTC, delisma commented on _pages/fr/communaute/procedure-contribution.md
>      link: /fr/communaute
Line 87: Il y a un lien qui fait référence à la page bibliothèque

2020-02-27 19:44 UTC, quidampepin commented on _pages/en/get-started/how.md
> +altLangPrefix: /debuter/comment
done

2020-02-27 19:44 UTC, quidampepin commented on _pages/en/get-started/latest.md
> +altLangPrefix: /debuter/changements
done

2020-02-27 19:44 UTC, quidampepin commented on _pages/en/get-started/information-architecture.md
> +altLangPrefix: /debuter/architecture-information
done

2020-02-27 19:44 UTC, quidampepin commented on _pages/en/get-started/policies.md
> +altLangPrefix: /debuter/politiques
done

2020-02-27 19:44 UTC, quidampepin commented on _pages/en/get-started/who.md
> +altLangPrefix: /debuter/qui
done

2020-02-27 19:45 UTC, quidampepin commented on _pages/fr/redaction/concevoir-succes-taches.md
> +- title: "Accueil"
done

2020-02-27 19:45 UTC, quidampepin commented on _pages/fr/communaute/procedure-contribution.md
>      link: /fr/communaute
done

2020-02-27 20:33 UTC, delisma approved these changes

2020-02-27 20:34 UTC, merged